### ISSUE TITLE
Problems encountered when analyzing BOHB using CAVE on Fedora Linux and Alpine Linux

### ISSUE THREAD

**Issue by 87302380** [automl/CAVE#248] opened 2019-07-03 10:58 UTC
Hi, I am trying to use CAVE to analyze the running results of BOHB, but I have encountered problems that I don't know how to solve. The program seems to be unable to start at all.
I follow the example, using the command :
```
cave --folders /home/parameters/result --file_format BOHB --output CAVE_BOHB_results
```
DEBUG:cave.cavefacade.CAVE:Output-dir 'CAVE_BOHB_results' was already created, call ignored
DEBUG:cave.cavefacade.CAVE:Running CAVE version 1.1.6
DEBUG:cave.utils.hpbandster2smac.HpBandSter2SMAC:<itertools.product object at 0x7f73862a86c0>
DEBUG:cave.utils.hpbandster2smac.HpBandSter2SMAC:Sampled 1 interpretations of "/home/parameters/result/configspace.pcs"
DEBUG:cave.utils.hpbandster2smac.HpBandSter2SMAC:[]
DEBUG:cave.utils.hpbandster2smac.HpBandSter2SMAC:Skipped 0 None- and 0 NaN-loss-values in BOHB-result
INFO:cave.utils.hpbandster2smac.HpBandSter2SMAC:Assuming BOHB treats target algorithms as deterministic (and does not re-evaluate)
INFO:smac.utils.io.cmd_reader.CMDReader:Output to CAVE_BOHB_results
DEBUG:smac.scenario.scenario.Scenario:SMAC and Scenario Options:
DEBUG:smac.scenario.scenario.Scenario:Output directory does not exist! Will be created.
DEBUG:smac.scenario.scenario.Scenario:Writing scenario-file to CAVE_BOHB_results/budget_9/scenario.txt.
INFO:smac.utils.io.cmd_reader.CMDReader:Output to CAVE_BOHB_results
DEBUG:smac.scenario.scenario.Scenario:SMAC and Scenario Options:
DEBUG:smac.scenario.scenario.Scenario:Output directory does not exist! Will be created.
DEBUG:smac.scenario.scenario.Scenario:Writing scenario-file to CAVE_BOHB_results/budget_27/scenario.txt.
INFO:smac.utils.io.cmd_reader.CMDReader:Output to CAVE_BOHB_results
DEBUG:smac.scenario.scenario.Scenario:SMAC and Scenario Options:
DEBUG:smac.scenario.scenario.Scenario:Output directory does not exist! Will be created.
DEBUG:smac.scenario.scenario.Scenario:Writing scenario-file to CAVE_BOHB_results/budget_81/scenario.txt.
INFO:smac.utils.io.cmd_reader.CMDReader:Output to CAVE_BOHB_results
DEBUG:smac.scenario.scenario.Scenario:SMAC and Scenario Options:
DEBUG:smac.scenario.scenario.Scenario:Output directory does not exist! Will be created.
DEBUG:smac.scenario.scenario.Scenario:Writing scenario-file to CAVE_BOHB_results/budget_243/scenario.txt.
DEBUG:cave.cavefacade.CAVE:Folders: ('CAVE_BOHB_results/budget_9', 'CAVE_BOHB_results/budget_27', 'CAVE_BOHB_results/budget_81', 'CAVE_BOHB_results/budget_243'); ta-exec-dirs: ['.']
DEBUG:cave.cavefacade.CAVE:Collecting data from CAVE_BOHB_results/budget_9.
DEBUG:cave.ConfiguratorRun.CAVE_BOHB_results/budget_9:Loading from 'CAVE_BOHB_results/budget_9' with ta_exec_dir '.'.
DEBUG:cave.reader:Creating scenario from '.'
DEBUG:smac.utils.io.cmd_reader.CMDReader:Deactivate output directory.
DEBUG:smac.utils.io.cmd_reader.CMDReader:Loading pcs as json from: CAVE_BOHB_results/budget_9/configspace.json
DEBUG:smac.scenario.scenario.Scenario:SMAC and Scenario Options:
DEBUG:cave.ConfiguratorRun.CAVE_BOHB_results/budget_9:RunHistory original runhistory only evaluated on 0/1 train-insts for default in folder CAVE_BOHB_results/budget_9
DEBUG:cave.ConfiguratorRun.CAVE_BOHB_results/budget_9:RunHistory original runhistory only evaluated on 0/1 test-insts for default in folder CAVE_BOHB_results/budget_9
DEBUG:cave.reader.configurator_run.ConfiguratorRun:No rng and no run_id given: using a random value to initialize run_id.
INFO:cave.reader.configurator_run.ConfiguratorRun:Optimizing a deterministic scenario for quality without a tuner timeout - will make SMAC deterministic!
INFO:smac.scenario.scenario.Scenario:No output directory for scenario logging specified -- scenario will not be logged.
INFO:smac.utils.io.traj_logging.TrajLogger:No output directory for trajectory logging specified -- trajectory will not be logged.

In addition, I have some doubts about the input format of BOHB.
The code in the document “Save a ConfigSpace config_space in a directory output_dir using”
does not work here for me

```
from ConfigSpace.read_and_write import pcs_new 
with open(output_dir, 'w') as fh:
    fh.write(pcs_new(config_space))
 
``` 

I am using：
```
with open(args.shared_directory+"/configspace.pcs", 'w') as fh:
    fh.write(pcs_new.write(w.get_configspace()))
```

I am not sure if this will change the output of the **configspace.pcs** file causing the error

**Comment by shukon** [comment] 2019-07-08 14:23
Hi. Is it possible for you to try using the `json`-format? There are some known issues with the pcs-format when it comes to complicated config-spaces. Try:

```
from ConfigSpace.read_and_write import json 
with open(args.shared_directory + "/configspace.json", 'w') as fh:
    fh.write(json.write(w.get_configspace()))
```

Also, what versions of BOHB, CAVE and ConfigSpace are installed? (you can check with `pip freeze`, if you're using pip as a version manager)

**Comment by 87302380** [comment] 2019-07-10 10:20
hello, I am using cave 1.1.6, ConfigSpace 0.4.10, hpbandster 0.7.4. I tried to use the json file to store the configspace. The problem still exists. There aren't too many changes to the log (just changed the read json file)

data [https://github.com/87302380/parameters/tree/master/result](url)
Output file: [https://github.com/87302380/parameters/tree/master/CAVE_BOHB_results](url)

DEBUG

DEBUG:cave.cavefacade.CAVE:Output-dir 'CAVE_BOHB_results' was already created, call ignored
DEBUG:cave.cavefacade.CAVE:Running CAVE version 1.1.6
DEBUG:cave.utils.hpbandster2smac.HpBandSter2SMAC:Detected and loaded "/home/lchen/parameters/result/configspace.json". No backup-cs necessary
DEBUG:cave.utils.hpbandster2smac.HpBandSter2SMAC:Skipped 0 None- and 0 NaN-loss-values in BOHB-result
INFO:cave.utils.hpbandster2smac.HpBandSter2SMAC:Assuming BOHB treats target algorithms as deterministic (and does not re-evaluate)
INFO:smac.utils.io.cmd_reader.CMDReader:Output to CAVE_BOHB_results
DEBUG:smac.scenario.scenario.Scenario:SMAC and Scenario Options:
DEBUG:smac.scenario.scenario.Scenario:Output directory does not exist! Will be created.
DEBUG:smac.scenario.scenario.Scenario:Writing scenario-file to CAVE_BOHB_results/budget_9/scenario.txt.
INFO:smac.utils.io.cmd_reader.CMDReader:Output to CAVE_BOHB_results
DEBUG:smac.scenario.scenario.Scenario:SMAC and Scenario Options:
DEBUG:smac.scenario.scenario.Scenario:Output directory does not exist! Will be created.
DEBUG:smac.scenario.scenario.Scenario:Writing scenario-file to CAVE_BOHB_results/budget_27/scenario.txt.
INFO:smac.utils.io.cmd_reader.CMDReader:Output to CAVE_BOHB_results
DEBUG:smac.scenario.scenario.Scenario:SMAC and Scenario Options:
DEBUG:smac.scenario.scenario.Scenario:Output directory does not exist! Will be created.
DEBUG:smac.scenario.scenario.Scenario:Writing scenario-file to CAVE_BOHB_results/budget_81/scenario.txt.
INFO:smac.utils.io.cmd_reader.CMDReader:Output to CAVE_BOHB_results
DEBUG:smac.scenario.scenario.Scenario:SMAC and Scenario Options:
DEBUG:smac.scenario.scenario.Scenario:Output directory does not exist! Will be created.
DEBUG:smac.scenario.scenario.Scenario:Writing scenario-file to CAVE_BOHB_results/budget_243/scenario.txt.
DEBUG:cave.cavefacade.CAVE:Folders: ('CAVE_BOHB_results/budget_9', 'CAVE_BOHB_results/budget_27', 'CAVE_BOHB_results/budget_81', 'CAVE_BOHB_results/budget_243'); ta-exec-dirs: ['.']
DEBUG:cave.cavefacade.CAVE:Collecting data from CAVE_BOHB_results/budget_9.
DEBUG:cave.ConfiguratorRun.CAVE_BOHB_results/budget_9:Loading from 'CAVE_BOHB_results/budget_9' with ta_exec_dir '.'.
DEBUG:cave.reader:Creating scenario from '.'
DEBUG:smac.utils.io.cmd_reader.CMDReader:Deactivate output directory.
DEBUG:smac.utils.io.cmd_reader.CMDReader:Loading pcs as json from: CAVE_BOHB_results/budget_9/configspace.json
DEBUG:smac.scenario.scenario.Scenario:SMAC and Scenario Options:
DEBUG:cave.ConfiguratorRun.CAVE_BOHB_results/budget_9:RunHistory original runhistory only evaluated on 0/1 train-insts for default in folder CAVE_BOHB_results/budget_9
DEBUG:cave.ConfiguratorRun.CAVE_BOHB_results/budget_9:RunHistory original runhistory only evaluated on 0/1 test-insts for default in folder CAVE_BOHB_results/budget_9
DEBUG:cave.reader.configurator_run.ConfiguratorRun:No rng and no run_id given: using a random value to initialize run_id.
INFO:cave.reader.configurator_run.ConfiguratorRun:Optimizing a deterministic scenario for quality without a tuner timeout - will make SMAC deterministic!
INFO:smac.scenario.scenario.Scenario:No output directory for scenario logging specified -- scenario will not be logged.
INFO:smac.utils.io.traj_logging.TrajLogger:No output directory for trajectory logging specified -- trajectory will not be logged.

In fact, what should cave output? A web page or document that contains analytical data?

**Comment by shukon** [comment] 2019-07-14 15:34
This is really weird, I cannot reproduce the problem. For me, the reports runs through without problems. The weird part of it is that there is no error-message. With CAVE 1.1.6 I get [this report](https://github.com/87302380/parameters/pull/1). And yes, it's a web-page with plots and analysis-data - checkout `report.html`.
The only thing I could imagine is missing installs that are silently caught with a sys.exit() in a submodule. Try to install swig, if you haven't yet. Try with:
`apt-get install build-essential swig`
or, if you use conda, try instead:
`conda install gxx_linux-64 gcc_linux-64 swig`.
I'll release 1.1.7 today or tomorrow. Please report, if the problem persists.

**Comment by 87302380** [comment] 2019-07-15 11:39
Hi, I tried installing swig and updated CAVE1.1.7 today. But the problem still exists.
If this can helps you, you can try to reproduce the problem on the Docker Playground.

[Docker Playground](https://labs.play-with-docker.com/)
(The docker playground provides an online virtual Linux environment)


Excellent if you know docker.
If you don't know, the following commands can help you quickly build the same environment.

After logging in to Docker Playground, click add new instance

```
docker pull python
docker run -dit python
docker exec -i -t id /bin/bash 
```
for example: If the id "4518ef6b0d77b",it is sufficient to use 451 instead of id here.
```
docker exec -i -t 451 /bin/bash 
```
```
cd /home
git clone https://github.com/87302380/parameters.git
cd /home/parameters/whl_data_3.7
pip3 install *.whl 
```
of course, you can also use it directly here.
```
pip3 install hpbandster
```
```
pip3 install cave
cd ..
apt-get update
apt-get install build-essential swig
cave --folders /home/parameters/result --file_format BOHB --output CAVE_BOHB_results
```
I think this should be able to reproduce the problem.

**Comment by 87302380** [comment] 2019-08-05 09:59
I found that this problem must come from the environment, but I don’t know where it is. 
I tried to repeat the operation on Ubuntu Linux, installed the same package, CAVE runs successfully.
The environments tried before were Fedora Linux and Alpine Linux.

**Comment by shukon** [comment] 2019-08-06 17:21
Thanks a lot for reporting that! I wasn't able to reproduce or figure out the problem yet, but it's good to know about environmental issues...

**Comment by shukon** [comment] 2019-10-04 19:01
Closing for now - feel free to reopen if there is news on this.

**Closed** 2019-10-04 19:01 UTC
