### ISSUE TITLE
Collection of issues based on SMAC data

### ISSUE THREAD

**Issue by mlindauer** [automl/CAVE#216] opened 2019-01-29 19:04 UTC
Hi,

Using CAVE on some SMAC data revealed quite some issues. (Sorry, I won't open a issue for each bug).

I have 20 SMAC runs and I used these as an input to CAVE. I used the current master branch of CAVE.

- [x]  Under "run-specific", I see only one single SMAC run (although I have 20) and I guess that the number of evaluated configurations only corresponds to a singe run? The stdout of CAVE found many more configurations. Maybe we want to add at least the stdev across the runs?
- [x]  "Best Configuration" does not show parameters that were inactive in the default but active in the incumbent (see goldsteinprice and lcb_par)
- [x]  If the number of instances is 0 or 1, eCDF and Scatter plots should be deactivated
- [x]  "Cost over time" There is a bug for the individual runs. 
- [x]  "Parallel Coordinates" does not use the most important parameter but always the same.
- [x]  "Ablation Importance" The importance values does not sum up to 100; not even close to it. Maybe we stop ablation too early if there are major interaction effects? (see attached branin data)

I attach three different SMAC benchmarks, both SMAC data and generated reports.

@shukon could please have a look into these issue and fix them.

Cheers,
Marius

[branin.zip](https://github.com/automl/CAVE/files/2809240/branin.zip)
[goldsteinprice.zip](https://github.com/automl/CAVE/files/2809249/goldsteinprice.zip)
[rosenbrock5d.zip](https://github.com/automl/CAVE/files/2809243/rosenbrock5d.zip)

**Comment by shukon** [comment] 2019-01-30 00:42
Ok, so I fixed some of the issues... however - and that is really strange, considering you used version 1.1.4 - I cannot reproduce the first and the fourth issue.
So what I checked should be fixed in #217.
Ablation seems a bit tricky to find out what's going wrong, I'll ask @AndreBiedenkapp and otherwise look into the data and the algorithm.

I'll have a look into the other issues... you used the master-branch, I suppose?

[goldstein_not_reproducable.zip](https://github.com/automl/CAVE/files/2810348/goldstein_not_reproducable.zip)
![cave2](https://user-images.githubusercontent.com/9417378/51950294-3489ff80-2430-11e9-91aa-c34757597d7b.png)
![cave1](https://user-images.githubusercontent.com/9417378/51950295-3489ff80-2430-11e9-9d5b-7eab9a4ee35f.png)

Thank you for the detailed feedback.

**Comment by shukon** [comment] 2019-01-30 10:56
@mlindauer well, the dev-branch fixes the things I marked in your initial comment. Why your version of the master-branch behaves differently from mine is on my stack today. Maybe I messed up my virtual-envs when testing... but honestly I don't know what it is yet.

**Comment by shukon** [comment] 2019-03-01 15:53
Last ones fixed with #230 and #231

**Closed by shukon** 2019-03-01 15:53 UTC
Labels: bug
