### ISSUE TITLE
Collection of issues (BOHB-CAVE)

### ISSUE THREAD

**Issue by mlindauer** [automl/CAVE#234] opened 2019-03-07 09:04 UTC
Hi,

we (Katha and I) looked into the BOHB-CAVE Report for the RL-task. The report is already very nice; nevertheless we found some little issues. 
@shukon could you please fix these:

- [x] If budgets are integers, can we please print them as ints? (If they are floats, please show at most 3 decimals)
- [x] Please remove the "combined" option in the configurator footprint plot. (my students were quite confused by them in the lecture and in fact a combined contour plot is misleading)
- [x] Could you please add uncertainty shaded areas across the BOHB runs in the cost over time plots (as always: 25% and 75 percentiles)
- [x] Why are the costs going up again in the cost-over-time plots? I would expect that the curves only go down
- [x] the curve for "all_budgets" continues longer than all individual budgets. Where are the data points coming from if not from the budgets?
- [x] the plots of fANOVA and LPI are not consistent. E.g., the learning rate is in the fANOVA plots nearly flat and has little uncertainty. The corresponding LPI plot shows much more variance and and a nice U-shape. I completely see the possibility that the plots do not show the same, but it is surprisingly not even a bit similar. Do you have an idea why? (maybe talk also with @AndreBiedenkapp about this point).
- [x] LPI has no uncertainty anymore. 

Cheers,
Marius

**Comment by shukon** [comment] 2019-03-07 12:07
Hi,
most of these make perfect sense to me and some are almost implemented already. I have a few points open to discussion, though: .
- the costs going up again are currently explained by the usage of an epm to estimate the cost... I think it will be better and less confusing to use the costs given in the trajectory, so I will return to that behavior. _Please note that the curve for "all budgets" might go up again when we switch to a higher budget (following the native behavior of BOHB, a higher budget is always better, even if the cost is worse, because we assume a higher fidelity)_
- the curve for all_budgets continues longer because the time-points for the trajectory are taken from two different sources (one is the converted trajectory, one is the Result-object of BOHB). I'm already on this and it should be fixed soon, though I need to change a few things in the data-flow.
- no idea, why the plots of fANOVA and LPI are not consistent... will investigate.
- there is still no meaningful uncertainty for the LPI... the problem is that we are already using the variances to determine the importance itself. So just using the variance over the means of the random forests does not work, because it's basically the same value. I've tried a few things and I'll try a few more before I will likely ask for help again.

Cheers!

**Comment by mlindauer** [comment] 2019-03-07 13:36
Hi,

Thanks for the fast reply!
One quick comment:

> the costs going up again are currently explained by the usage of an epm to estimate the cost... I think it will be better and less confusing to use the costs given in the trajectory, so I will return to that behavior. 

That's fine. However, please consider that might not be possible for SMAC data with instances. So, we need a switch between BOHB and SMAC here!?


Cheers,
Marius

**Comment by shukon** [comment] 2019-03-07 14:01
> However, please consider that might not be possible for SMAC data with instances. So, we need a switch between BOHB and SMAC here!?
I actually think this might make sense...

**Comment by shukon** [comment] 2019-03-18 22:24
A few remarks:
>  Could you please add uncertainty shaded areas across the BOHB runs in the cost over time plots (as always: 25% and 75 percentiles)

std's are now present on all BOHB-curves (and consistent, because all values are reused from the BOHB-result). Is this sufficient? Percentiles might be very confusing with only a couple of runs.

> the plots of fANOVA and LPI are not consistent

Not sure. For learning rate I only find fANOVA plots that are log on x-scale and only LPI-plots that are linear (at least from the ones generated by default). Will check if putting both on log/lineas changes anything.

> LPI has no uncertainty anymore.

See https://github.com/automl/CAVE/issues/221

**Comment by mlindauer** [comment] 2019-04-01 14:58
Hi,

What is the status of the remaining issues?

I found some more little things in the last report you send to Katha and me:

- [ ] Budget correlation has no tool tip. Please add one
- [ ] the plot is empty in the beginning and it is not intuitive to click on the table. we need a more obvious way to select the budget combinations such that the scatter plot shows something
- [ ] the configurator footprint has no time slider anymore and the static plots are also missing. Could you please re-add at least one of the two again.

Cheers,
Marius

**Comment by shukon** [comment] 2019-04-02 19:28
Hi Marius,
I'm still awaiting some sort of feedback my proposal for the LPI-problem. I think I forgot to include a mention - I'm sorry. [Look here.](https://github.com/automl/CAVE/issues/221#issuecomment-474126992)
For budget correlation I propose [this setup](https://github.com/automl/CAVE/tree/issue/234-budget-correlation):
![budget_correlation](https://user-images.githubusercontent.com/9417378/55428852-5451b700-558a-11e9-9332-033c4f4a136a.png)
And I'm not sure what you mean - for me, it's either the time-slider or the static plots. If you mean the static-plots don't get generated, you will need to install phantomjs (`npm install phantomjs-prebuilt`). You can generate a report with timeslider by adding `--cfp_timeslider on`.
And on the inconsistency, the main point I'm seeing is that LPI estimates the cost significantly lower than fanova...

**Comment by mlindauer** [comment] 2019-04-03 11:02
The new correlation menu looks nice.

Regarding the time-slider and static plots for the configurator footprints:
The last report you sent to Katha and me did not include a time-slider and static plots. Maybe you deactivated that for generating this report?

**Comment by shukon** [comment] 2019-04-03 16:21
> The last report you sent to Katha and me did not include a time-slider and static plots. Maybe you deactivated that for generating this report?

Probably. I'll send a new one asap.

**Comment by shukon** [comment] 2019-04-08 14:32
Ok, so I'm pretty sure https://github.com/automl/ParameterImportance/commit/16981ec48e4bd65237814d3e864531b301365e22 fixed the differences in LPI and fanova somewhat and https://github.com/automl/ParameterImportance/pull/103 should fix LPI-uncertainty.

**Closed** 2019-05-09 09:05 UTC
